<x-app-layout>
    <x-slot name="header"><h2 class="font-semibold text-xl text-gray-800 leading-tight">{{ __('Partner Commissions') }}</h2></x-slot>
    <div class="space-y-6"><div class="container-page">
        <div class="flex gap-4 mb-6">
            <div class="stat-card flex-1"><p class="text-sm text-gray-500">Pending</p><p class="text-2xl font-bold text-yellow-600">&#8377;{{ number_format($totals['pending'] ?? 0) }}</p></div>
            <div class="stat-card flex-1"><p class="text-sm text-gray-500">Approved</p><p class="text-2xl font-bold text-blue-600">&#8377;{{ number_format($totals['approved'] ?? 0) }}</p></div>
            <div class="stat-card flex-1"><p class="text-sm text-gray-500">Paid</p><p class="text-2xl font-bold text-green-600">&#8377;{{ number_format($totals['paid'] ?? 0) }}</p></div>
        </div>
        <div class="card p-4 mb-6"><form method="GET" class="flex flex-wrap gap-4"><select name="status" class="input-field w-auto"><option value="">All Status</option><option value="pending" {{ request('status')==='pending'?'selected':'' }}>Pending</option><option value="approved" {{ request('status')==='approved'?'selected':'' }}>Approved</option><option value="paid" {{ request('status')==='paid'?'selected':'' }}>Paid</option></select><input type="text" name="search" placeholder="Search..." value="{{ request('search') }}" class="input-field w-64"><button type="submit" class="btn-primary text-sm">Search</button></form></div>
        <div class="card overflow-hidden"><table class="w-full"><thead class="bg-gray-50"><tr><th class="px-6 py-3 text-left text-xs font-medium uppercase">Partner</th><th class="px-6 py-3 text-left text-xs font-medium uppercase">Deal</th><th class="px-6 py-3 text-left text-xs font-medium uppercase">Amount</th><th class="px-6 py-3 text-left text-xs font-medium uppercase">Status</th><th class="px-6 py-3 text-left text-xs font-medium uppercase">Date</th></tr></thead><tbody class="divide-y">@forelse($commissions as $c)<tr class="hover:bg-gray-50"><td class="px-6 py-4 text-sm">{{ $c->partner->name ?? 'N/A' }}</td><td class="px-6 py-4 text-sm text-gray-600">#{{ $c->deal_id ?? 'N/A' }}</td><td class="px-6 py-4 text-sm font-medium">&#8377;{{ number_format($c->amount) }}</td><td class="px-6 py-4"><span class="badge badge-{{ $c->status === 'paid' ? 'success' : ($c->status === 'pending' ? 'warning' : 'info') }}">{{ ucfirst($c->status) }}</span></td><td class="px-6 py-4 text-sm text-gray-500">{{ $c->created_at->format('M d, Y') }}</td></tr>@empty <tr><td colspan="5" class="px-6 py-12 text-center text-gray-500">No commissions found.</td></tr>@endforelse</tbody></table><div class="px-6 py-4 border-t">{{ $commissions->withQueryString()->links() }}</div></div>
    </div></div>
</x-app-layout>
