import defaultTheme from 'tailwindcss/defaultTheme';
import forms from '@tailwindcss/forms';
import typography from '@tailwindcss/typography';

/** @type {import('tailwindcss').Config} */
export default {
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
    ],

    safelist: [
        // CMS content pattern: gradient variants
        'from-terracotta-950',
        'via-terracotta-900',
        'to-terracotta-800',
        // CMS content pattern: hover transforms
        'hover:-translate-y-1',
        'hover:-translate-y-0.5',
        'hover:translate-y-0',
        'hover:shadow-2xl',
        'hover:shadow-xl',
        'hover:shadow-lg',
        // CMS content pattern: transitions
        'transition-all',
        'transition',
        'transition-transform',
        'transition-shadow',
        'duration-200',
        'duration-300',
        'ease-out',
        // CMS content pattern: blur
        'blur-3xl',
        'blur-2xl',
        // CMS content pattern: w/h sizes used in CMS
        'w-96',
        'h-96',
        'w-80',
        'h-80',
        'w-14',
        'h-14',
        'w-12',
        'h-12',
        'w-7',
        'h-7',
        'w-5',
        'h-5',
        // CMS content pattern: grid
        'grid-cols-1',
        'md:grid-cols-2',
        'lg:grid-cols-4',
        'md:grid-cols-3',
        'lg:grid-cols-2',
        // CMS content pattern: spacing
        'gap-6',
        'gap-8',
        'gap-12',
        'space-y-4',
        'space-y-6',
        'space-y-3',
        'space-y-2',
        // CMS content pattern: padding
        'p-8',
        'p-6',
        'p-4',
        'px-8',
        'px-4',
        'py-20',
        'py-24',
        'py-28',
        'py-16',
        'py-4',
        'py-1.5',
        'md:py-28',
        'md:py-32',
        'md:py-24',
        'pt-8',
        'pt-16',
        'pb-8',
        'pb-20',
        // CMS content pattern: text sizes
        'text-5xl',
        'text-7xl',
        'md:text-6xl',
        'lg:text-7xl',
        'text-4xl',
        'md:text-5xl',
        'lg:text-6xl',
        'text-3xl',
        'md:text-4xl',
        'lg:text-5xl',
        'text-2xl',
        'md:text-3xl',
        // CMS content pattern: text colors
        'text-white',
        'text-white/80',
        'text-white/60',
        'text-gray-600',
        'text-gray-700',
        'text-gray-900',
        'text-terracotta-950',
        'text-terracotta-600',
        'text-terracotta-700',
        'text-terracotta-900',
        'text-terracotta-500',
        // CMS content pattern: bg
        'bg-white',
        'bg-gray-50',
        'bg-gray-100',
        'bg-terracotta-50',
        'bg-terracotta-100',
        'bg-terracotta-500',
        'bg-terracotta-900',
        'bg-terracotta-950',
        'bg-white/10',
        'bg-white/20',
        'bg-terracotta-600/20',
        'bg-terracotta-500/15',
        'bg-white/5',
        'bg-gray-800',
        'bg-gray-950',
        // CMS gradient patterns
        'from-terracotta-950',
        'via-terracotta-900',
        'to-terracotta-800',
        'from-terracotta-900',
        'via-terracotta-700',
        'to-terracotta-500',
        'from-terracotta-950',
        'via-terracotta-900',
        'to-terracotta-800',
        'from-terracotta-900',
        'to-terracotta-700',
        'from-terracotta-950',
        'via-terracotta-900',
        'to-terracotta-800',
        // CMS borders
        'border',
        'border-gray-100',
        'border-gray-200',
        'border-white/10',
        'border-white/20',
        'border-terracotta-500',
        'border-terracotta-200/50',
        // CMS rounded
        'rounded-2xl',
        'rounded-xl',
        'rounded-lg',
        'rounded-full',
        // CMS flex/grid
        'flex',
        'flex-col',
        'sm:flex-row',
        'items-center',
        'justify-center',
        'justify-between',
        'inline-flex',
        'inline-block',
        // CMS gaps
        'gap-2',
        'gap-3',
        'gap-4',
        'gap-6',
        'gap-8',
        'gap-12',
        // CMS max-width
        'max-w-7xl',
        'max-w-4xl',
        'max-w-3xl',
        'max-w-2xl',
        'max-w-xl',
        'max-w-xs',
        // CMS misc
        'mb-1',
        'mb-2',
        'mb-3',
        'mb-4',
        'mb-5',
        'mb-6',
        'mb-8',
        'mb-10',
        'mb-16',
        'mt-2',
        'mt-6',
        'mt-8',
        'my-2',
        'tracking-tight',
        'tracking-wider',
        'leading-relaxed',
        'leading-tight',
        'uppercase',
        'lowercase',
        'capitalize',
        // CMS yellow/lemon theme
        'text-yellow-300',
        'bg-yellow-300/10',
        'bg-yellow-300',
        'border-yellow-300/20',
        'antialiased',
        'relative',
        'absolute',
        'inset-0',
        'inset-x-0',
        'top-0',
        '-top-40',
        '-bottom-40',
        '-right-40',
        '-left-40',
        'top-1/2',
        'left-1/2',
        '-translate-x-1/2',
        '-translate-y-1/2',
        'pointer-events-none',
        'overflow-hidden',
        'animate-pulse',
        'opacity-10',
        'opacity-5',
        'hidden',
        'md:inline',
        'lg:inline',
        'w-2',
        'h-2',
        'list-disc',
        'list-decimal',
        'pl-4',
    ],

    theme: {
        extend: {
            typography: {
                DEFAULT: {
                    css: {
                        fontSize: '1.0625rem',
                        lineHeight: '1.8',
                        color: '#374151',
                        'h2': {
                            fontWeight: '700',
                            fontSize: '1.625rem',
                            color: '#2A0F0A',
                            marginTop: '3rem',
                            marginBottom: '1rem',
                            paddingBottom: '0.75rem',
                            borderBottom: '2px solid #FFB0A1',
                            letterSpacing: '-0.01em',
                        },
                        'h3': {
                            fontWeight: '600',
                            fontSize: '1.25rem',
                            color: '#451911',
                            marginTop: '2rem',
                            marginBottom: '0.75rem',
                        },
                        'h4': {
                            fontWeight: '600',
                            fontSize: '1.1rem',
                            color: '#6B2918',
                            marginTop: '1.5rem',
                            marginBottom: '0.5rem',
                        },
                        'p': {
                            marginBottom: '1.25rem',
                        },
                        'strong': {
                            color: '#2A0F0A',
                            fontWeight: '600',
                        },
                        'a': {
                            color: '#E35336',
                            fontWeight: '500',
                            textDecoration: 'underline',
                            textUnderlineOffset: '2px',
                            '&:hover': {
                                color: '#C74428',
                            },
                        },
                        'ul': {
                            marginTop: '0.75rem',
                            marginBottom: '1.25rem',
                        },
                        'ol': {
                            marginTop: '0.75rem',
                            marginBottom: '1.25rem',
                        },
                        'ul > li': {
                            paddingLeft: '0.25rem',
                            marginBottom: '0.375rem',
                        },
                        'ol > li': {
                            paddingLeft: '0.25rem',
                            marginBottom: '0.375rem',
                        },
                        'ul > li::marker': {
                            color: '#E35336',
                        },
                        'ol > li::marker': {
                            color: '#E35336',
                            fontWeight: '600',
                        },
                        'li > p': {
                            marginBottom: '0.5rem',
                        },
                    },
                },
            },
            fontFamily: {
                sans: ['Figtree', ...defaultTheme.fontFamily.sans],
            },
            colors: {
                terracotta: {
                    50: '#FEF3F0',
                    100: '#FFB0A1',
                    200: '#FF9480',
                    300: '#FF7060',
                    400: '#E35336',
                    500: '#E35336',
                    600: '#C74428',
                    700: '#9E3A26',
                    800: '#6B2918',
                    900: '#451911',
                    950: '#2A0F0A',
                },
            },
            boxShadow: {
                'card': '0 1px 3px 0 rgb(0 0 0 / 0.04), 0 1px 2px -1px rgb(0 0 0 / 0.04)',
                'card-hover': '0 10px 25px -3px rgb(0 0 0 / 0.08), 0 4px 6px -4px rgb(0 0 0 / 0.04)',
                'nav': '0 1px 3px 0 rgb(0 0 0 / 0.05)',
                'elevated': '0 20px 40px -12px rgb(69 25 17 / 0.15)',
            },
            borderRadius: {
                '2xl': '1rem',
                '3xl': '1.5rem',
            },
            animation: {
                'fade-in': 'fadeIn 0.5s ease-out',
                'slide-up': 'slideUp 0.5s ease-out',
                'slide-down': 'slideDown 0.3s ease-out',
                'scale-in': 'scaleIn 0.2s ease-out',
            },
            keyframes: {
                fadeIn: {
                    '0%': { opacity: '0' },
                    '100%': { opacity: '1' },
                },
                slideUp: {
                    '0%': { opacity: '0', transform: 'translateY(20px)' },
                    '100%': { opacity: '1', transform: 'translateY(0)' },
                },
                slideDown: {
                    '0%': { opacity: '0', transform: 'translateY(-10px)' },
                    '100%': { opacity: '1', transform: 'translateY(0)' },
                },
                scaleIn: {
                    '0%': { opacity: '0', transform: 'scale(0.95)' },
                    '100%': { opacity: '1', transform: 'scale(1)' },
                },
            },
        },
    },

    plugins: [forms, typography],
};
